SwissDataScienceCenter/renku-notebooks

src/notebooks_service.py

wait for server to spawn before redirecting

---

src/notebooks_service.py

redirect to existing server if already running

---

helm-chart/renku-notebooks/templates/deployment.yaml
src/notebooks_service.py

Requires: https://github.com/SwissDataScienceCenter/renku/pull/301

Added capability to use private images from gitlab

---

.gitignore
helm-chart/renku-notebooks/templates/deployment.yaml
helm-chart/renku-notebooks/values.yaml
run-telepresence.sh

make it possible to use telepresence to develop the notebooks service component

add telepresence script

---

helm-chart/renku-notebooks/templates/deployment.yaml
helm-chart/renku-notebooks/templates/secrets.yaml
helm-chart/renku-notebooks/values.yaml
src/notebooks_service.py
src/templates/server_status.html

Handle the situation where a user tries to re-start a server that is in the process of shutting down. 
todo:

Status handling

---

Dockerfile
Pipfile
Pipfile.lock
helm-chart/renku-notebooks/templates/secrets.yaml
src/__init__.py

use gunicorn as the http server

---

travis-deploy.sh

Fix Travis deploy for real

---

jupyterhub/spawners.py

jh: combine group and project permissions

---

helm-chart/renku-notebooks/values.yaml
jupyterhub/spawners.py

spawner: avoid infinite loop

---

jupyterhub/spawners.py

jh: do not force lowercase

---

jupyterhub/spawners.py

This commit got left off the previous PR.

Fixing #45 again

---

.travis.yml
helm-chart/chartpress.yaml
helm-chart/renku-notebooks/values.yaml
singleuser/cuda.Dockerfile

* Added an image with cuda 9.2, for GPU enabled notebooks
* Made travis run chartpress to validate all image builds

Base image for enabling work with nvidia GPUs

---

src/notebooks_service.py

authenticate with jh token in request header

---

src/notebooks_service.py

Set cache timeout to 0 for server_options endpoint

---

.travis.yml
helm-chart/chartpress.yaml

Pull singleuser images before building them

---

helm-chart/renku-notebooks/values.yaml
jupyterhub/spawners.py
src/notebooks_service.py

skip smudge by default and provide server_options override

---

jupyterhub/spawners.py

Install LFS globally and disable or enable smudge based on options. 
addresses https://github.com/SwissDataScienceCenter/renku/issues/343
closes #93

disable smudge globally

---

helm-chart/renku-notebooks/Chart.yaml
travis-deploy.sh

Prep 0.3.0

---

helm-chart/renku-notebooks/Chart.yaml
jupyterhub/spawners.py
src/notebooks_service.py

Adds project-specific metadata (namespace/project/branch/commit)
to the servers json.
closes #125 
closes #127

feat: add /servers for user server listing

---

jupyterhub/spawners.py

Go to your project settings on GitLab and select CI/CD.
Set environment variables that you would like to pass to the launched notebook.
closes #120

feat: include GitLab project variables

---

jupyterhub/spawners.py
src/notebooks_service.py

fix: add project id to annotations

---

git-clone/Dockerfile
git-clone/entrypoint.sh
jupyterhub/requirements-k8s.txt
jupyterhub/spawners.py

This PR adds lifecycle hooks to the jupyterhub spawners.
closes #96 
closes #126

feat: added pre-stop post-start hooks

---

src/notebooks_service.py

fix: do not fail on empty annotations

---

helm-chart/renku-notebooks/templates/deployment.yaml
helm-chart/renku-notebooks/templates/role.yaml
jupyterhub/spawners.py
src/notebooks_service.py

The logs for the notebook pod can be fetched from
`<SERVICE_PREFIX>/<namespace>/<project>/<commit-sha>/logs`

Add notebook server logs endpoint

---

helm-chart/renku-notebooks/templates/deployment.yaml

fix: correct indentation of periodSeconds

---

helm-chart/renku-notebooks/templates/configmap.yaml
helm-chart/renku-notebooks/templates/deployment.yaml
helm-chart/renku-notebooks/values.yaml

fix: do not create sentry configmap if no value

---

helm-chart/renku-notebooks/templates/deployment.yaml
src/notebooks_service.py

Closes #95.
---
Merge together with https://github.com/SwissDataScienceCenter/renku-ui/pull/460

Add scheme and hostname to notebook server urls

---

helm-chart/renku-notebooks/values.yaml
jupyterhub/spawners.py

This PR modifies the location of the attached volume that contains the cloned project to `/work/<project-name>`.

use a system-agnostic workdir

---

jupyterhub/spawners.py

Pod annotations pass through the same code that makes pod names dns-safe - this means that we were shortening them in a way that made them unusable. ~~This PR fixes the situation by only running pod and pvc templates through the expansion code/filter.~~ This PR fixes the situation by removing the custom `expand_user_properties` code and instead just handling the pod name length individually.

fix annotation bug

---

renku_notebooks/api/notebooks.py
renku_notebooks/util/gitlab_.py
renku_notebooks/util/kubernetes_.py

Adds more logs and does minor refactoring to notebook service to make debugging easier in future.

refactor: add more logs

---

renku_notebooks/api/notebooks.py
tests/test_notebook.py

* return JSON data instead of TEXT
* change the default lines to 250
fix #224

feat: update server_logs api

---

.travis.yml
.travis/travis-deploy.sh
.travis/travis-functions.sh

Resolves #233
Note that the travis CLI did some auto-modifications to .travis-ci.yaml.

build: automatically update renku-notebooks dependency in renku

---

Pipfile
Pipfile.lock
helm-chart/renku-notebooks/Chart.yaml
renku_notebooks/util/gitlab_.py
tests/conftest.py

closes #273 
running on rok.dev.renku.ch

fix: use registry API to look up if image exists

---

git-clone/entrypoint.sh
helm-chart/renku-notebooks/templates/configmap.yaml
jupyterhub/spawners.py

Fixes https://github.com/SwissDataScienceCenter/renku-notebooks/issues/280
My understanding was that in anonymous sessions `JUPYTERHUB_AUTHENTICATOR` is set to a value other than `gitlab`. I used this to distinguish anonymous sessions from authenticated ones.

feat: autosave/restore only when session is authenticated

---

renku_notebooks/util/gitlab_.py
tests/conftest.py
tests/test_notebook.py

fix: use lowercase image repository names

---

helm-chart/renku-notebooks/templates/ingress.yaml

Same as https://github.com/SwissDataScienceCenter/renku/pull/1446.

fix(charts): correct proxy-public port in ingress

---

helm-chart/minikube-values.yaml
helm-chart/renku-notebooks/templates/deployment.yaml
helm-chart/renku-notebooks/values.yaml
run-telepresence.sh

Some small improvements to the charts (see commit messages).

chore(charts): several improvements

---

.pre-commit-config.yaml
helm-chart/renku-notebooks/requirements.lock
helm-chart/renku-notebooks/templates/deployment.yaml
helm-chart/renku-notebooks/templates/hpa.yaml
helm-chart/renku-notebooks/values.yaml

Provides an optional HPA template to enable autoscaling, configurable through the values file.

feat: enable pod autoscaling

---

helm-chart/renku-notebooks/values.yaml

To still fix/verify: disable image puller

Disable userScheduler and userPlaceholder

---

helm-chart/renku-notebooks/templates/deployment.yaml
helm-chart/renku-notebooks/values.yaml
renku_notebooks/__init__.py
renku_notebooks/config.py

Adds the sentry environment on initialization of the sentry sdk.

chore: add sentry environment

---

.github/workflows/ci.yml

Replace deprecated set-env commands in the GitHub actions

---

.github/workflows/acceptance-tests.yml

Adds an action that allows acceptance tests to be requested during PR review. 
/deploy
closes #524

chore: add acceptance test action

---

jupyterhub/spawners.py
renku_notebooks/api/notebooks.py

closes #365 
Not sure if I should retry more than once or add a period when I just wait before retrying.
I went for the simplest case of not waiting and just retrying once.

fix: retry when creating notebook fails with 500

---

.github/workflows/acceptance-tests.yml

chore: fix deploy cleanup

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

Since a couple of the fixes dont have an issue, I've linked the PR instead.

chore: prep 0.8.9 release

---

.github/workflows/acceptance-tests.yml
.github/workflows/ci.yml

Add missing env variable and pin imported action versions.

chore(ci): fix missing variable and pin CI actions

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: changelog for 0.8.12

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: update change log and chart version

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prepare 0.8.18 release

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prepare 1.1.0 release

---

renku_notebooks/api/classes/server.py

fix: add ingress annotation to each session so iframes work

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
helm-chart/renku-notebooks/requirements.lock
helm-chart/renku-notebooks/requirements.yaml

chore: prep 1.1.1 release

---

.github/workflows/ci.yml

chore: fix chart publishing

---

renku_notebooks/api/classes/storage.py

fix(app): do not delete autosaves before restoring

---

.github/workflows/acceptance-tests.yml

chore: fix ci deployment pipeline

---

.github/workflows/acceptance-tests.yml
Pipfile
Pipfile.lock
renku_notebooks/api/classes/user.py

closes #816 
I could not get this error to trigger at all. Keycloak would not let me change my email with special characters like that. And when I add special characters in my name on Keycloak things worked even before this fix.
@ableuler what part of your profile did you change to replicate this?
I think that using a dedicated package for this is overkill but probably the safest thing to do.
/deploy

fix(app): use pyjwt to decode token

---

renku_notebooks/api/classes/server.py

fix(app): apply CPU limits to user sessions

---

helm-chart/renku-notebooks/requirements.lock
helm-chart/renku-notebooks/requirements.yaml

chore(chart): bump amalthea to 0.2.2

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.2.1 release

---

renku_notebooks/api/classes/server.py

fix(app): return proper values for image and repository

---

helm-chart/renku-notebooks/templates/statefulset.yaml
helm-chart/renku-notebooks/values.yaml
renku_notebooks/__init__.py
renku_notebooks/config.py

Followed the example from renku python: https://github.com/SwissDataScienceCenter/renku-python/pull/2560/files

chore(app): enable sentry performance monitoring

---

helm-chart/renku-notebooks/requirements.yaml
helm-chart/renku-notebooks/templates/statefulset.yaml
helm-chart/renku-notebooks/templates/test.yaml
helm-chart/renku-notebooks/values.yaml
renku_notebooks/api/amalthea_patches/cloudstorage.py
renku_notebooks/api/classes/server.py
renku_notebooks/api/notebooks.py
renku_notebooks/api/schemas.py
tests/integration/test_session_creation.py

fix(app)!: change s3 bucket naming

---

helm-chart/renku-notebooks/templates/statefulset.yaml
helm-chart/renku-notebooks/values.yaml
renku_notebooks/__init__.py
renku_notebooks/config.py

Align sentry values with the other renku repositories.
Reference: https://swiss-data-science.slack.com/archives/G67N59QL8/p1643901194490749
/deploy

build: update sentry values

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.4.1 release

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: 1.6.0 release

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.6.1 release

---

helm-chart/renku-notebooks/values.yaml
renku_notebooks/api/amalthea_patches/git_proxy.py
renku_notebooks/api/amalthea_patches/git_sidecar.py
renku_notebooks/api/amalthea_patches/init_containers.py

This further locks down the security context.

chore: set runAsNonRoot to true

---

CHANGELOG.md

Adds an explanation about potential problems that may occur with the helm chart if an old section of the values.yaml file is present.
I already updated this in the release notes on github.

chore: amend changelog

---

renku_notebooks/api/schemas/custom_fields.py
tests/unit/test_custom_fields.py

/deploy renku-ui=1791-servers-resources #persist

fix(app): serialize cpu and gpu request to number

---

renku_notebooks/api/classes/server.py
renku_notebooks/api/schemas/config_server_options.py
renku_notebooks/api/schemas/custom_fields.py
renku_notebooks/api/schemas/server_options.py
renku_notebooks/api/schemas/servers_get.py
tests/unit/test_custom_fields.py

fix(app): properly deserialize server options

---

renku_notebooks/api/schemas/servers_get.py

In some cases the reason for why the sessions is unschedulable cannot be parsed and does not appear.
This was occuring because the parsing of the unschedulable message was too strict. Now the parsing is a bit more flexible and if it fails then the unparsed message is returned. Which is better than not seeing a message at all.

fix(app): parse unschedulable resources message

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.8.2 release

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.8.3 release

---

README.md

See [here](https://github.com/SwissDataScienceCenter/renku-notebooks/blob/fix-sequence-diagram/README.md) for fixed verison

chore: fix sequence diagram in readme

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
helm-chart/renku-notebooks/requirements.yaml

chore: prep 1.9.0 release

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
helm-chart/renku-notebooks/values.yaml

chore: prep 1.9.1 release

---

renku_notebooks/api/notebooks.py

This uses the same webargs library for validation similar to other endpoints on the server.
Also I added the docs for this so that it shows up in swagger.

chore(app): document max lines for getting logs

---

git_services/git_services/init/cloner.py

fix(app): catch upper/lowercase out of space error

---

helm-chart/renku-notebooks/requirements.yaml

Updating to the latest version of amalthea

feat(app): update amalthea to 0.5.2

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.10.0 release

---

.github/workflows/ci.yml
.github/workflows/integration-tests.yml
poetry.lock

🤞 I really hope this works because waiting for the exact same image to build 10 times in the same action is crazy.

chore(ci): add docker layer caching

---

git_services/git_services/cli/__init__.py
git_services/git_services/init/cloner.py
git_services/git_services/init/config.py
git_services/git_services/sidecar/commands/base.py
git_services/tests/conftest.py
git_services/tests/test_autosave.py
git_services/tests/test_git_cli.py
git_services/tests/test_rpc_server.py

Fixes a bug where non-standard characters in a user's full name where crashing the git commands in the init containers.
Example stack trace:
```
Traceback (most recent call last):                                                                                                                                                                                                                                                                                          │
│   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main                                                                                                                                                                                                                                                │
│     return …
```

fix(sidecar): escape characters in user full name

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.11.0 release

---

git_services/git_services/init/cloner.py
git_services/git_services/init/config.py

fix(app): respect git lfs autofetch flag

---

git_services/git_services/init/cloner.py
git_services/git_services/init/config.py

/deploy #persist renku=fix-do-not-reload-page-after-failing-to-click-terminal

fix(sidecar): properly set and unset lfs auth

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.11.1 release

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.12.0 release

---

renku_notebooks/api/notebooks.py

fix: accept zero as max_lines parameter for logs

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

New release
/deploy #persist renku=master

chore: prep 1.13.0 release

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

/deploy #persist renku-gateway=master

chore: prep 1.14.0 release

---

renku_notebooks/api/schemas/version.py

fix(app): show if ssh enabled in /version

---

helm-chart/renku-notebooks/templates/ssh.yaml

fix ssh service type

---

renku_notebooks/api/classes/server_manifest.py

The funny thing is it took me 20 mins to realize the return statement is missing after noticing the manifestation of the bug.

fix(app): missing return statement

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
helm-chart/renku-notebooks/requirements.yaml

chore: prep 1.15.0 release

---

git-https-proxy/config/config.go

Fixes this error:
```
  |   | 2023-03-02 16:16:01 | {"log":"\u0009/src/config/config.go:159 +0xaf4 ","stream":"stderr","time":"2023-03-02T15:16:01.317253742Z"}
  |   | 2023-03-02 16:16:01 | {"log":"created by github.com/SwissDataScienceCenter/renku-notebooks/git-https-proxy/config.ParseEnv ","stream":"stderr","time":"2023-03-02T15:16:01.317241681Z"}
  |   | 2023-03-02 16:16:01 | {"log":"\u0009/src/config/config.go:310 +0xb1 ","stream":"stderr","time":"2023-03-02T15:16:01.317229952Z"}
  |   | 2023-03-02 16:16:01 | {"log":"github.com/SwissDataScienceCenter/renku-notebooks/git-https-proxy/config.(*GitProxyConfig).periodicTokenRefresh(0xc00010add0) ","stream":"stderr","time":"2023-03-02T15:16:01.317217412Z"}
  |   | 2023-03-02 16:16:01 | …
```

fix(git-proxy): refresh token expiry check

---

helm-chart/renku-notebooks/values.yaml

Not sure why I made this enabled by default.
Now it is disabled by default.

chore(chart): make ssh disabled by default

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.15.1 release

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep 1.15.2 release

---

.github/dependabot.yaml

chore: add dependabot updates for auxiliary services

---

git_services/git_services/init/cloner.py

fix: do not fail on submodule errors

---

.github/workflows/combine-dependabot-updates.yml

manually triggered action to make a single dependabot PR that deals with poetry.lock properly

chore: add action to combine dependabot PRs

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml

chore: prep release 1.16.0

---

renku_notebooks/api/classes/crc.py
renku_notebooks/api/notebooks.py
renku_notebooks/api/schemas/server_options.py

fix(app): parse old server options in request

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
pyproject.toml

chore: prep 1.18.0 release

---

git_services/git_services/sidecar/gunicorn.conf.py

fix(sidecar): fix renku save

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
pyproject.toml

chore: prep 1.18.1 release

---

renku_notebooks/api/classes/image.py
tests/unit/test_public_image_checks.py

fix(app): handle OCI image manifests

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
helm-chart/renku-notebooks/values.yaml

chore: prep 1.20.0 release

---

README.md
renku_notebooks/api/amalthea_patches/general.py
renku_notebooks/api/schemas/server_options.py

/deploy renku-data-services=fix-tolerations-affinities

fix: properly patch tolerations and affinities

---

git_services/git_services/init/cloner.py

This caused sessions that are hibernated to lose work.

fix: do not remove the repo in cloning step

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
helm-chart/renku-notebooks/values.yaml

chore: prep 1.20.2 release

---

renku_notebooks/api/classes/auth.py
renku_notebooks/api/classes/k8s_client.py
renku_notebooks/api/notebooks.py
renku_notebooks/util/kubernetes_.py

This fixes the issues we have had with expiring Gitlab access tokens.
/deploy renku=fix-gitlab-token-in-sessions

fix: inject new set of tokens when the session is resumed

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
helm-chart/renku-notebooks/values.yaml

chore: prep 1.20.3 release

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
helm-chart/renku-notebooks/values.yaml

chore: prep 1.21.0 release

---

renku_notebooks/api/classes/server.py
renku_notebooks/api/notebooks.py
renku_notebooks/config/static.py
renku_notebooks/util/kubernetes_.py

Add support for sessions without any repository mounted.
/deploy #notest renku=build/new-sessions renku-data-services=leafty/134-default-url renku-ui=leafty/start-session-zero-repos

Add support for sessions without any repository mounted

---

git_services/git_services/init/clone.py
git_services/git_services/init/cloner.py
git_services/git_services/init/config.py
git_services/tests/test_init_clone.py
renku_notebooks/api/amalthea_patches/general.py
renku_notebooks/api/amalthea_patches/git_proxy.py
renku_notebooks/api/amalthea_patches/git_sidecar.py
renku_notebooks/api/amalthea_patches/init_containers.py
renku_notebooks/api/amalthea_patches/jupyter_server.py
renku_notebooks/api/classes/server.py
renku_notebooks/api/classes/user.py
renku_notebooks/api/notebooks.py
renku_notebooks/api/schemas/repository.py
renku_notebooks/api/schemas/servers_post.py
renku_notebooks/config/__init__.py
renku_notebooks/config/static.py
renku_notebooks/util/kubernetes_.py
tests/unit/test_server_class/test_manifest.py

Fixes #1800.
/deploy renku=release-0.49.0

feat: support for renku 2 sessions

---

git_services/git_services/init/clone.py
git_services/git_services/init/cloner.py
git_services/git_services/init/config.py
git_services/tests/test_init_clone.py
renku_notebooks/api/amalthea_patches/general.py
renku_notebooks/api/amalthea_patches/git_proxy.py
renku_notebooks/api/amalthea_patches/git_sidecar.py
renku_notebooks/api/amalthea_patches/init_containers.py
renku_notebooks/api/amalthea_patches/jupyter_server.py
renku_notebooks/api/classes/server.py
renku_notebooks/api/classes/user.py
renku_notebooks/api/notebooks.py
renku_notebooks/api/schemas/repository.py
renku_notebooks/api/schemas/servers_post.py
renku_notebooks/config/__init__.py
renku_notebooks/config/static.py
renku_notebooks/util/kubernetes_.py
tests/unit/test_server_class/test_manifest.py

See https://github.com/SwissDataScienceCenter/renku/issues/3475.
/deploy renku=release-0.50.x renku-data-services=build/new-sessions-demo renku-ui=build/new-sessions

feat: support for Renku 2.0 sessions

---

CHANGELOG.md
helm-chart/renku-notebooks/Chart.yaml
helm-chart/renku-notebooks/values.yaml

Just changelog updates and version bumps for the new release.

chore: prep 1.22.1 release

---

renku_notebooks/api/classes/data_service.py

Fixes #1878.
Before: https://github.com/SwissDataScienceCenter/renku-notebooks/actions/runs/9123959576/job/25087457498
After: https://github.com/SwissDataScienceCenter/renku-notebooks/actions/runs/9124690365/job/25089537171
/deploy renku=release-0.52.x renku-ui=main renku-data-services=main

fix: do not setup any git provider for anonymous sessions

---

renku_notebooks/api/amalthea_patches/git_sidecar.py

Removes a "None" folder added in Renku 2.0 sessions:
```yaml
- env:
- name: GIT_RPC_MOUNT_PATH
value: /work/None
```
/deploy renku=release-0.52.x

fix: remove subpath "None" from sidecar container for Renku 2.0 sessions

---

git-https-proxy/tokenstore/main.go

feat: changes for jupyter free sessions

---

resource_schema_migrations/migration_1.py

was nested one level too deep
/deploy

fix: only patch jupyter servers once in migration

---

renku_notebooks/api/classes/image.py

Migration of
https://github.com/SwissDataScienceCenter/renku-data-services/pull/526
This should fix the image tests we see failing in other prs.
/deploy

fix: correct implementation for multi-arch images

---

renku_notebooks/api/schemas/cloud_storage.py

PR to add the necessary configuration for supporting Polybox and SwitchDrive storage.
/deploy

feat: add config to support polybox and switchDrive storage

---

Dockerfile
Dockerfile.tests
git_services/Dockerfile.init
git_services/Dockerfile.sidecar
secrets-mount/Dockerfile

build: pin poetry in Dockerfile

---

git_services/git_services/init/clone.py
git_services/git_services/init/cloner.py
git_services/git_services/init/config.py
git_services/tests/test_init_clone.py
renku_notebooks/api/amalthea_patches/init_containers.py

closes https://github.com/SwissDataScienceCenter/renku-data-services/issues/619
closes https://github.com/SwissDataScienceCenter/renku-data-services/issues/631
tested on https://github.com/SwissDataScienceCenter/renku-data-services/pull/643 PR

fix: mount repos in working dir, not (pvc)mount path

---

.github/workflows/acceptance-tests.yml

V2 tests were not running correctly. This fixes it
/deploy renku=release-0.66.0

ci: add cypress acceptance tests folder

---

.github/workflows/acceptance-tests.yml

chore: make CI pipelines deploy to Azure

---

git_services/git_services/init/clone.py
git_services/git_services/init/cloner.py
git_services/git_services/init/config.py

See: https://github.com/SwissDataScienceCenter/renku-data-services/pull/938.

fix: allow git proxy port to be configured
