SwissDataScienceCenter/renku-notebooks

- helm-chart/renku-notebooks/templates/deployment.yaml
- helm-chart/renku-notebooks/values.yaml
This PR adds the possibility to use a private registry for the `renku-notebooks` image.
Private image example:
https://gitlab.com/renku/renku-notebooks/container_registry
then:
```bash
$ helm upgrade -i renku-notebooks \
--namespace test \
--set image.repository="registry.gitlab.com/renku/renku-notebooks" \
--set image.tag="pull-secrets" renku-notebooks \
--set global.renku.domain=$(minikube ip)
```
You will see the image pull fail.
```bash
$ kubectl -n test create secret docker-registry regcred \
--docker-server=registry.gitlab.com \
--docker-username="gitlab+deploy-token-5965" \
--docker-password="***" \
--docker-email="***"
$ helm upgrade -i renku-notebooks \
--namespace test \
--set image.repository="registry.gitlab.com/renku/renku-notebooks" \
--set image.tag="pull-secrets" …
```
> image pull secrets

- Pipfile
- Pipfile.lock
- helm-chart/renku-notebooks/Chart.yaml
- helm-chart/renku-notebooks/templates/deployment.yaml
- helm-chart/renku-notebooks/templates/role.yaml
- helm-chart/renku-notebooks/templates/rolebinding.yaml
- helm-chart/renku-notebooks/templates/serviceaccount.yaml
- helm-chart/renku-notebooks/values.yaml
- src/notebooks_service.py
This PR resolves #19.
The service account is functional, to test it when renku-notebooks is deployed:
```bash
$ kubectl -n renku run my-shell -i --tty --image ubuntu:16.04 bash
$ exit
$ kubectl -n renku edit deploy my-shell
<Put 'serviceAccountName: renku-notebooks' in the podspec>
$ kubectl -n renku attach my-shell-75d8cbc9f4-9sktv -c my-shell -i -t # it's a new pod
$ apt update && apt install -y curl
$ curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
$ chmod +x ./kubectl
$ mv ./kubectl /usr/local/bin/kubectl
$ kubectl get po # works
$ kubectl get cm # is denied
```
> [Chart] Create a service account to watch pods

- .dockerignore
- Pipfile
- Pipfile.lock
- helm-chart/renku-notebooks/templates/_helpers.tpl
- helm-chart/renku-notebooks/templates/deployment.yaml
- src/notebooks_service.py
- src/templates/server_status.html
> make the main endpoint more CRUD

- src/notebooks_service.py
closes #27 
~~This has the side-effect of JupyterLab messing up the URL. The server starts and opens fine with the correct notebook displayed, but the URL gets changed to `<host>/lab/jupyterhub/user/<user>/<server-name>` instead of keeping `<host>/jupyterhub/user/<user>/<server-name>/lab`~~
The incorrect redirect seems to have been caused by an extra slash in the URL... 
This also resolves https://github.com/SwissDataScienceCenter/renku-ui/issues/273
> open the notebook in jupyterlab

- Dockerfile
- helm-chart/chartpress.yaml
- helm-chart/renku-notebooks/templates/deployment.yaml
- helm-chart/renku-notebooks/values.yaml
- jupyterhub/jupyterhub-k8s.Dockerfile
- jupyterhub/spawners.py
- singleuser/Dockerfile
- singleuser/requirements.txt
- src/notebooks_service.py
Move the logic regarding image selection out of the spawner and into the notebook service. The spawner should just launch whichever image is given to it.
> Refactor image build check 

- Dockerfile
- helm-chart/chartpress.yaml
- helm-chart/renku-notebooks/templates/deployment.yaml
- helm-chart/renku-notebooks/values.yaml
- jupyterhub/jupyterhub-k8s.Dockerfile
- jupyterhub/spawners.py
- singleuser/Dockerfile
- singleuser/R.Dockerfile
- singleuser/requirements.txt
- src/notebooks_service.py
This PR enables RStudio launches from renku. 
* creates a renku-enabled rstudio image that is compatible with jupyter (based on the  `nbrsessionproxy` `Dockerfile`)
* adds the ability to specify `default_url` as a query parameter. If the `POST` request includes `?default_url=/rstudio` in the request url, RStudio is launched automatically. This should be included in the UI as part of https://github.com/SwissDataScienceCenter/renku-ui/issues/308.
closes #57
> Enable RStudio launches

- Dockerfile
- Pipfile
- Pipfile.lock
- helm-chart/minikube-values.yaml
- helm-chart/renku-notebooks/Chart.yaml
- helm-chart/renku-notebooks/templates/configmap.yaml
- helm-chart/renku-notebooks/templates/deployment.yaml
- helm-chart/renku-notebooks/values.yaml
- jupyterhub/spawners.py
- src/notebooks_service.py
This PR allows the notebooks service setup to include default server options -- and to override them upon server launch. The options are set in `values.yaml` and written into a file in the container via a `configMap`. 
The options can be queried by a UI client using `GET <service_prefix>/<namespace>/<project>/<commit-sha>/server_options` -- the returned JSON can be used to render a template. 
The client should return only the option and the value, e.g. if the JSON server from `server_options` is
```
{
"serverOptions":
{ 
"resources":
{ 
"cpu_limit":
{
"default": 1,
"type": int,
"range": [1,4]
}
}
}
}
```
The client should use 
```
{
"serverOptions":
{
"resources":
{
"cpu_limit": "1"
}
}
}
```
as the json data in the POST request to spawn the server. 
---
closes #66 
closes #65 
addresses …
> enable passing server options for notebook server launch

- helm-chart/renku-notebooks/templates/configmap.yaml
- helm-chart/renku-notebooks/values.yaml
Adds option to include `SENTRY_DSN` configuration.
> build(helm): extra config map with env for KubeSpawner

- .gitignore
- Pipfile
- Pipfile.lock
- README.rst
- helm-chart/chartpress.yaml
- helm-chart/renku-notebooks/Chart.yaml
- helm-chart/renku-notebooks/requirements.lock
- helm-chart/renku-notebooks/requirements.yaml
- helm-chart/renku-notebooks/values.yaml
- jupyterhub/Dockerfile
- jupyterhub/jupyterhub-k8s.Dockerfile
- src/notebooks_service.py
* bump jupyterhub dependency to 0.8.0
* rebuild images with updated JH
* parametrize JH version in `chartpress.yaml`
closes #111
> Update JupyterHub chart dependency and images

- Pipfile
- Pipfile.lock
- src/notebooks_service.py
sample response:
```
curl https://rok.dev.renku.ch/jupyterhub/services/notebooks/user -H "Accept: application/json" --verbose
*   Trying 86.119.25.180...
* TCP_NODELAY set
* Connected to rok.dev.renku.ch (86.119.25.180) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: rok.dev.renku.ch
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /jupyterhub/services/notebooks/user HTTP/1.1
> Host: rok.dev.renku.ch
> User-Agent: curl/7.54.0
> Accept: application/json
>
< HTTP/1.1 401 UNAUTHORIZED
< Server: nginx/1.15.8
< Date: Wed, 13 Mar 2019 13:23:51 GMT
< Content-Type: application/json
< Content-Length: 48
< Connection: keep-alive
< Strict-Transport-Security: max-age=15724800; includeSubDomains
<
* …
```
> fix: return 401 on unauthorized non-browser requests

- helm-chart/renku-notebooks/templates/deployment.yaml
- helm-chart/renku-notebooks/values.yaml
We should not be doing these checks in the notebooks service,
but instead in the frontend. The notebooks service should just
launch whatever image it's given.
closes #70
> fix: remove imageBuildTimeout

- jupyterhub/spawners.py
This PR makes the memory limit equal to the memory request. In practice this means that as soon as the notebook kernel approaches the memory limit, the kernel is restarted. Importantly, the user's session is not affected. 
---
closes #147
> Enforce memory limit for user pods

- jupyterhub/requirements.txt
The requirements file had `>=0.9.6` meaning that the image built by travis had JH 1.0.0 instead of 0.9.6. Keep this one until we've done some more testing.
> build: fix jh version

- helm-chart/renku-notebooks/templates/deployment.yaml
- helm-chart/renku-notebooks/templates/registry-secret.yaml
- helm-chart/renku-notebooks/values.yaml
Note that this change allows non-root admin tokens to be used. This should make it easier to rotate them periodically. 
```
gitlab:
registry:
username: a_user
token: 12345
```
closes #167
> refactor(charts): move registry secret from renku repo

- helm-chart/renku-notebooks/templates/registry-secret.yaml
- helm-chart/renku-notebooks/values.yaml
Quick fix for the newly-refactored secret - ignore the secret template if the username *and* token are not set.
> fix: update registry secret template

- renku_notebooks/api/notebooks.py
- renku_notebooks/util/jupyterhub_.py
- tests/test_notebook.py
Instead of putting the project name and commit sha into the server name, we form the servername by hashing the string 
```
{namespace}{project}{commit-sha}{ref}
```
where `ref` for the time being is assumed to be a branch but could be a tag, for instance.
The resulting pod name is something like `jupyter-rokroskar-9ecaa0eeed735403` (16-digit hash) and the server name is just the hash, i.e. in this case `rokroskar/9ecaa0eeed735403`. 
---
closes #90
> feat: spawn new server for different branch

- .flake8
- README.rst
- jupyterhub/spawners.py
- renku_notebooks/api/auth.py
- renku_notebooks/api/notebooks.py
- renku_notebooks/config.py
- renku_notebooks/util/jupyterhub_.py
- renku_notebooks/util/kubernetes_.py
- tests/conftest.py
- tests/test_auth.py
- tests/test_notebook.py
Uses Kubernetes API to get information about running servers instead of using JupyterHub's. This should remove the load from the JupyterHub and increase the number of concurrent servers.
The JSON response from the `/servers` endpoint has changed because we don't have some information that used to come fro the JupyterHub.
This also include some code from the https://github.com/SwissDataScienceCenter/renku-notebooks/pull/181 PR so that one can be closed without merging.
---
closes #181
> 177 use k8s api for queries

- git-clone/entrypoint.sh
- jupyterhub/spawners.py
- renku_notebooks/util/kubernetes_.py
The autosave branch is recovered only when its `branch` and `commit-sha` match with the those of notebook's. See https://github.com/SwissDataScienceCenter/renku-notebooks/issues/187.
This also fixes an uncaught exception which was introduced in https://github.com/SwissDataScienceCenter/renku-notebooks/pull/185.
This was tested on a repo with two branches for various scenarios.
> 187 recover from autosave only when branch commit match

- git-clone/entrypoint.sh
- helm-chart/renku-notebooks/templates/configmap.yaml
- renku_notebooks/util/kubernetes_.py
Fixes a bug in check for autosaved branch commit-sha where it was checking against the long commit-sha instead of the short one.
> fix: use shortened commit-sha to check for an autosave match

- .pre-commit-config.yaml
- .travis.yml
- chartpress.yaml
- travis-deploy.sh
Add support for running `chartpress --reset` as a git pre-commit hook using the [`pre-commit`](https://pre-commit.com) package. 
To try it out: 
```bash
pipenv install --deploy 
pipenv run pre-commit install
pipenv run pre-commit run chartpress
```
Trying to commit a modified chart value that is handled by `chartpress` results in
```bash
git commit -am 'commiting woop'
black................................................(no files to check)Skipped
Flake8...............................................(no files to check)Skipped
chartpress reset.........................................................Failed
hookid: chartpress
Files were modified by this hook. Additional output:
$> git log -n 1 --pretty=format:%h -- . . jupyterhub singleuser
$> git log -n 1 --pretty=format:%h -- . …
```
> chore: use pre-commit hooks for chartpress --reset

- helm-chart/renku-notebooks/templates/role.yaml
- renku_notebooks/api/notebooks.py
- renku_notebooks/util/kubernetes_.py
- tests/conftest.py
- tests/test_notebook.py
This PR enable to force-delete a pod by bypassing JupyterHub API and using K8s API directly. When a delete request has a `force` parameter which its value is set to `true`, notebook services uses the K8s API directly and kills the pod.
Make sure that you use this method as a last resort (i.e. after trying to DELETE normally).
Closes https://github.com/SwissDataScienceCenter/renku-notebooks/issues/150. 
Addresses https://github.com/SwissDataScienceCenter/renku-ui/issues/361
> 150 can force delete pods

- Pipfile
- Pipfile.lock
- README.rst
- renku_notebooks/__init__.py
- run-telepresence.sh
The `run-telepresence` script was a bit outdated.
The second commit includes the code to easily debug though VScode.
> restore telepresence script

- renku_notebooks/util/jupyterhub_.py
- tests/conftest.py
Server name created by JupyterHub includes up to 46 chars from the reference project name. This is a possible quick solution to SwissDataScienceCenter/renku-ui#584 *apparently* without any significative side effect.
Preview available here: https://lorenzotest.dev.renku.ch
Relevant changes: the server name is different, so the JupyterLab url will also be affected accordingly
Here is the url comparison of a project named `zurich-bikes-tutorial`
fix SwissDataScienceCenter/renku-ui#584
> feat: use project name in the notebook URL

- renku_notebooks/api/notebooks.py
- renku_notebooks/util/kubernetes_.py
During the spawning phase, querying kubernetes logs API may result in a predictable error. This PR returns a plaintext message instead of a `400` error response
> feat: gracefully handle predictable k8s api errors when querying for logs

- Pipfile
- Pipfile.lock
pin chartpress version to avoid using the new charts naming convention
> build: pin chartpress version

- helm-chart/renku-notebooks/templates/configmap.yaml
Use the environment starting commit to compose the autosaved branches.
A preview is available on https://lorenzotest.dev.renku.ch and can easily be tested from the UI
From any project with >= 2 commits (e.g. fork https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/zurich-bikes-tutorial/environments) start a new environment from an old commit, do any work (e.g. `touch aaa`) and stop the notebook without further actions. Trying to start a new environment from the same commit will result in the autosave message, while trying to start from the latest commit won't display any message. The behavior is currently inverted on https://dev.renku.ch/
fix #219
> fix: reference environment starting commit on autosave branches

- .github/workflows/ci.yml
- Pipfile.lock
- renku_notebooks/api/auth.py
- tests/test_notebook.py
Updates to werkzeug have caused some of the behavior to change: 
* the `is_xhr` attribute is no longer present in the `request` object
* if a URL includes double slashes it is now automatically redirected to the url without the extra slash, returning a `308` instead of `404`
> chore: update werkzeug behavior

- git-clone/entrypoint.sh
- jupyterhub/spawners.py
The environment variable `LFS_AUTO_FETCH` is set to the string `"True"` when the lfs fetch checkbox is ticked: this is why the condition was always testing false when checking for `= 1`, therefore ignoring the setting.
I am not sure if this changed recently or if it simply didn't work in the past. Maybe we could fix this by making `LFS_AUTO_FETCH = true` (or `1`) instead of testing for `== "True"`
fix #227
***TESTING***
Preview available here: https://lorenzotest.dev.renku.ch/
* try to start notebooks on a project with lfs files, once with and once without selecting the lfs fetch checkbox
* verify with `git lfs ls-files` that lfs files are available
> fix: check lfs setting as a string

- jupyterhub/spawners.py
- tests/conftest.py
Add the repository link to the pod's annotations and return it when querying the `GET /servers` endpoint.
```
"annotations": {
"cni.projectcalico.org/podIP": "10.42.5.38/32",
"hub.jupyter.org/servername": "flights-tutorial-d991bad2",
"hub.jupyter.org/username": "lorenzo.cavazzi.tech",
"renku.io/branch": "master",
"renku.io/commit-sha": "c581b56edc53b18df6d352241590d6be1a1cf51e",
"renku.io/namespace": "lorenzo.cavazzi.tech",
"renku.io/projectId": "1228",
"renku.io/projectName": "flights-tutorial",
"renku.io/repository": "https://dev.renku.ch/gitlab/lorenzo.cavazzi.tech/flights-tutorial"
},
```
Needed by SwissDataScienceCenter/renku-ui#493
> feat: add repository url to annoations

- renku_notebooks/util/kubernetes_.py
- tests/conftest.py
Add the requested resources info to the `GET /servers` API response. This is an example, the new part is in the attribute `resources`
```
{
"servers": {
"flights-tutorial-d991bad2": {
"annotations": {
[...]
},
"name": "flights-tutorial-d991bad2",
"resources": {
"cpu": "0.1",
"memory": "1073741824"
},
"started": "2020-03-12T16:54:30.000000Z",
"state": {
"pod_name": "jupyter-lorenzo-2ecavazzi-2etech-flights-2dtutorial-2dd991bad2"
},
"status": {
[...]
},
"url": "https://lorenzo.dev.renku.ch/jupyterhub/user/lorenzo.cavazzi.tech/flights-tutorial-d991bad2/"
}
}
}
```
UPDATE: It's possible to test the change in `lorenzotest` deplyoment: https://lorenzotest.dev.renku.ch/
fix #223
> feat: add requested resources info to servers endpoint

- jupyterhub/spawners.py
This PR constrains the gids used for the container processes. It's currently running on rok.dev.renku.ch. 
With this PR, the notebook container runs as gid 100 and sets the user to be a member of groups 100 and 1000.
> feat: contrain the container gids

- helm-chart/make-values-tmp.py
- helm-chart/renku-notebooks/Chart.yaml
- helm-chart/renku-notebooks/templates/deployment.yaml
- helm-chart/renku-notebooks/templates/ingress.yaml
- helm-chart/renku-notebooks/values.yaml
- jupyterhub/requirements.txt
- jupyterhub/spawners.py
- renku_notebooks/api/auth.py
- renku_notebooks/api/notebooks.py
- renku_notebooks/config.py
- renku_notebooks/util/gitlab_.py
- renku_notebooks/util/kubernetes_.py
- tests/test_notebook.py
- Enable the use of tmpauthenticator for Jupyterhub authentication.
This enables notebook sessions for logged-out users. Closes #171
- Enable logged in users without write access to a project to start
notebook servers from the project. Closes #275
> feat: allow unprivileged and anonymous users to launch servers

- helm-chart/make-values-tmp.py
This is needed for some deployments that dont have `gitlab.url` configured
> Fix for gitlab URL

- git-clone/entrypoint.sh
- jupyterhub/spawners.py
This PR restructures the git-clone entrypoint to inject the user's credentials into a credential-helper file so as to hide the token from the remote URL. 
This configuration is running on https://rok.dev.renku.ch
To test, launch an environment in the test deployment above and try to push a chance to one of your projects. See that `git remote -v` shows no oauth token. 
closes #313
> chore: obscure oauth token

- renku_notebooks/api/notebooks.py
This PR fixes the problem that users with an underscore in their username have seen when launching notebooks from private repos.
Closes #393.
> fix(app): escape username in registry secret name

- .github/dependabot.yaml
This PR adds the pattern that we already use on the renku-gateway for grouping dependency update PRs.
> chore(ci): move to github dependabot

- jupyterhub/spawners.py
Closes #155 
Number of env variables on renkulab.io freshly made project:
```
work ❯ test1 ▶ master ▶ $ ▶ env | wc -l
258
```
After setting enableServiceLinks to false:
```
work ❯ test10 ▶ master ▶ $ ▶ env | wc -l
66
```
> Remove service links from user pods

- helm-chart/renku-notebooks/templates/user-pod-egress.yaml
- helm-chart/renku-notebooks/values.yaml
Closes #413 
This is a continuation of this PR: https://github.com/SwissDataScienceCenter/renku/pull/1541 which was posted on the renku repo but it should have been here. 
I retested the proposed changes in the code to make sure it works. Currently this is in place at tasko.dev.renku.ch.
As expected once the policy is active, the user cannot even get a 401 (Unauthorized) response from any of the internal kubernetes pods/components that are in the same node/cluster. However egress from the user pod to the internet and to DNS services (both inside and outside of the cluster) is not restricted at all.
> feat: restrict user pod egress

- helm-chart/renku-notebooks/templates/cronjob.yaml
I forgot completely about this, my bad. Virginia came across this issue, see [here](https://swiss-data-science.slack.com/archives/G67N59QL8/p1603811018093200).
I currently tested that this will deploy in my namespace with the changes. I am not sure exactly what I have to change to get a longer name without making a new namespace. I did test by decreasing the limit further so that I see the cronjob in my namespace show up with a truncated name and it works.
I also made sure that the container name that cronjob creates is less than the 63 character limit.
The math for the truncation is as follows:
- cronjob name: 
- limit of 52 characters 
- minus 22 characters for `-cull-registry-secrets` 
- = 30
- name of each pod launched by cronjob: 
- limit of 63 characters 
- minus 22 characters for …
> bug: Truncate secret-cull cronjob and pod names to be within k8s limits

- Pipfile
- Pipfile.lock
- cull_secrets/clean_user_registry_secrets.py
The latest version of `black` requires a later version of `pytoml` than the `jupyterhub-traefik-proxy` (used only in tests) can handle.
> chore: fix dependency conflict by pinning black

- .github/workflows/ci.yml
The test-chart action uses the helm version 2.16.1. We need to update to version >= 2.17.0 to prevent it from failing as in https://github.com/SwissDataScienceCenter/renku-notebooks/runs/1649563015
Reference: https://helm.sh/blog/new-location-stable-incubator-charts/
> ci: update helm url

- renku_notebooks/util/kubernetes_.py
closes #496 
Basically with the addition of the http proxy container in the pod the status of the pod cannot be determined just from one container. In addition even with a single container we had a problem where the "Terminating" status was not properly recognized. It seems that the only way that the "Terminating" status can be recognized is by checking whether `pod.metadata.deletionTimestamp` is None or not.
> fix: properly recognize pod status when terminating

- cull_secrets/clean_user_registry_secrets.py
I noticed that the cull image pull secrets jobs were failing with the following message.
```
INFO:root:Checking for user registry secrets whose names match the regex: .+-registry-[a-z0-9-]{36}$
Traceback (most recent call last):
File "/cull_secrets/clean_user_registry_secrets.py", line 187, in <module>
main()
File "/cull_secrets/clean_user_registry_secrets.py", line 183, in main
remove_user_registry_secret(args.namespace, k8s_client, args.age_hours_minimum)
File "/cull_secrets/clean_user_registry_secrets.py", line 112, in remove_user_registry_secret
for annotation_key in POD_ANNOTATIONS
File "/cull_secrets/clean_user_registry_secrets.py", line 112, in <listcomp>
for annotation_key in POD_ANNOTATIONS
AttributeError: 'NoneType' object has no attribute 'keys'
```
The problem is occurring …
> fix: checking and deleting secrets without annotations and labels

- helm-chart/renku-notebooks/values.yaml
So I saw the `helm lint` failed after the latest changes. But the line that causes the failure has not been changed in months.
I think this is occurring because jupyterhub was upgraded.
This is the line in the jupyterhub helm chart _helpers.tpl that causes [this problem](https://github.com/SwissDataScienceCenter/renku-notebooks/runs/1707349028):
```
{{- else if eq (typeOf $value) "string" -}}
- name: {{ $key | quote }}
value: {{ $value | quote | println }}
{{- else }}
{{- printf "?.extraEnv.%s had an unexpected type (%s)" $key (typeOf $value) | fail }}
{{- end }}
```
It seems that before non-string values were allowed in the extraEnv part, but not anymore. The lint command passes after this.
> fix: extraEnv requires only string values now

- renku_notebooks/api/notebooks.py
Fixes: 
- https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/4937/events/1175997ba7994c0a9a23e07645d8ed7f/
- https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/4936/events/8274de23f69f43db9e0ac3772350a3cd/
This occurs because of leftover logger.error statements that I was using when working on the code and dubugging. These are not real errors. These should have been removed.
> fix: remove unnecessary log error calls

- renku_notebooks/api/schemas.py
- tests/conftest.py
This will address the following errors:
- https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/4940/events/57bfd7f7151d4d5bb11d08825e054325/
- https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/4939/events/9c1dce46c5c94a8a9ee3511f367b2082/
The issues were occurring because:
- now we also have an `ephemeral-storage` variable that we did not know before in the pod resources
- the timestamp that when the pod starts can be `null` sometimes instead of a timestamp
> fix: pod resources schema

- README.rst
- helm-chart/minikube-values.yaml
closes #144 
The only thing I had to fix was the description of the endpoints and the instructions to start renku-notebooks with minikube and an existing gitlab deployment.
I tested that with the new instructions one can deploy renku-notebooks with minikube and launch and access a server.
> chore: update documentation

- jupyterhub/spawners.py
At first we suspected that the cause of these types of [errors](https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/4994/activity/?environment=renku-ci&environment=renku-dev&project=4&query=is%3Aunresolved) is just the jupyterhub pod in k8s not being properly updated and holding an old config or something like that. Because killing the `hub-*` pod would always resolve the issue. 
However we see that killing the `hub-*` pod only temporarily resolves things. This is because the `KubeSpawner` keeps instances of all servers and sometimes reuses them. Therefore by simply appending to the list of `extra_containers` in the spawner we were getting in a situation (in some edge case) where the spawner which already contains `https-proxy` as an extra container is reused and the …
> fix: duplicate https proxy containers

- .github/workflows/acceptance-tests.yml
- .github/workflows/ci.yml
- Update renku requirements only when a new version is released.
- Run ci deployements / acceptance tests against the main branch in renku.
closes #534.
> chore: adapt ci/cd logic

- helm-chart/renku-notebooks/values.schema.json
- renku_notebooks/api/custom_fields.py
- renku_notebooks/api/notebooks.py
- renku_notebooks/api/schemas.py
- renku_notebooks/util/misc.py
- tests/test_notebook.py
closes #71 
So I implemented evaluation on the helm chart values but only for the server options portion. I will add a new issue to add it for the whole values.yaml file.
I also added more detailed validation (in line with the values.yaml validation) for the API.
I did some digging online to see if marshmallow can parse jsonschema and convert to marshmallow type schemas and it cannot unfortunately. There is a library that can convert a marshmallow schema to jsonschema but it cannot include the custom validation we need for some of the server options stuff. So I think we unfortunately have to have this kind of duplication.
This is deployed at https://tasko.dev.renku.ch/
> feat: validate server options

- renku_notebooks/api/schemas.py
Fixes these kind of errors on limited: https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/5096/?environment=renku-limited&project=4&referrer=alert_email
This is occurring because I did not test with an environment that actually has a gpu. And in the response after the sessions is created the JH reports not only the memory and cpu but also the gpu that was requested. The gpu was not added in the schemas so it is crashing on limited.
This should fix that.
/deploy
> fix: unknown gpu field in resources request

- renku_notebooks/__init__.py
- renku_notebooks/api/custom_fields.py
- renku_notebooks/api/schemas.py
So when I was implementing this feature, which prevents you from launching a notebook with more cpu/memory than what is specified in the server options, I forgot that the `defaultUrl` option should not fall in this category. Some people use this to launch notebooks or dashboards, etc on other urls.
/deploy
> fix: do not check defaultUrl against list of server options

- renku_notebooks/api/schemas.py
- tests/test_schema_validation.py
So the schema validation for the annotations seems to be a bit too strict.
This will allow unknown annotations (not mentioned in the schema) to not trigger an error and to be included in the response.
It should fix this issue.
https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/5156/?environment=dslab2021renkulab&project=4&referrer=alert_email
> fix: allow and include unknown annotations in schema

- cull_secrets/clean_user_registry_secrets.py
- jupyterhub/spawners.py
- renku_notebooks/api/notebooks.py
- renku_notebooks/api/schemas.py
- renku_notebooks/util/kubernetes_.py
- tests/conftest.py
- tests/test_clean_user_registry_secrets.py
- tests/test_schema_validation.py
So I think I came across something similar before but I noticed a bug on Friday through sentry ([link here](https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/5210/?environment=renkulab&project=4&referrer=alert_email)) that is the result of a really long project name. We add the project name in the user pod labels but the labels in k8s cannot be longer than 63 characters so when someone with a long project name tries to launch a server it fails.
The way I resolved this is that in the labels I cut down the project name and username to a max of 63 characters. These are only used to filter the user pods when deleting the registry pull secrets. Then I also added the full project name and username in the pod annotations - which have no length limit. The annotations are …
> fix: labels values are too long for k8s

- .github/workflows/acceptance-tests.yml
Add the possibility to provide details to the `/ deploy` command.
Info: https://github.com/SwissDataScienceCenter/renku/pull/2073/files?short_path=e969017#diff-e969017621edbe724f851ca789090af791987d4a7386f2eb4ec5f85c58156baa
/deploy #notest renku-ui=0.11.8
> ci: enforce deploy string command

- renku_notebooks/config.py
According to profiles run on the /servers endpoint, the execution time is mainly spent on two functions in the user class code: `_get_hub_username` and `_get_hub_user`. The _get_hub_username function just uses the `user_for_token` method of HubOAuth from jupyterhub. And if we adjust the caching that is provided by jupyterhub in HubOAuth then we can save about ~150-300 ms. These are two profiles for the call to the same endpoint by the same user. I assume that in the second one the cache for HubOauth was used and the execution is roughly halved.
The default max cache age for HubOAuth from Jupyterhub is 300 sec (https://jupyterhub.readthedocs.io/en/stable/api/services.auth.html?highlight=huboauth#jupyterhub.services.auth.HubOAuth.cache_max_age)
Long execution time profile
Short execution …
> fix: increase huboauth caching from 1min to 5min

- .github/workflows/acceptance-tests.yml
- git-clone/entrypoint.sh
This PR fixes a problem which occurrs when two conditions were met simultaneously:
1. The git lfs auto fetch option is set to true on session start
2. There are files in LFS.
In this case, git lfs adds a line like `lfs.https://renkulab.io/gitlab/andreas/test-lfs-problem.git/info/lfs.access=basic` to the repos `.git/config` when pulling the files during the init container. Because of this configuration, git prompts for username and password later when a user tries to push from the main session container. Removing this config at the end of the init container entry point delegates authentication back to the git http proxy.
/deploy
> fix: unset lfs auth mode in init container

- renku_notebooks/__init__.py
- renku_notebooks/api/classes/server.py
- renku_notebooks/api/classes/user.py
- renku_notebooks/api/notebooks.py
- renku_notebooks/api/schemas.py
- tests/conftest.py
- tests/test_autosaves.py
closes #584 
Made according to the swagger spec that @lorenzo-cavazzi specified [here](https://app.swaggerhub.com/apis/lorenzo-cavazzi/renku-notebooks/0.1.0)
Example output:
```json
{
"autosaves": [
{
"branch": "master",
"commit": "993875e950de66a1074d58cb8ce89b54f41a0941",
"date": "2021-03-08T16:04:08+00:00",
"pvs": false
}
],
"pvsSupport": true
}
```
/deploy
> feat: endpoint for autosave information

- renku_notebooks/api/schemas.py
This fixes a bug that resulted when an old session pod with some missing annotations was encountered. The bug happened in marshmallow and it resulted because annotations have `.` characters in their keys but marshmallow automatically converts keys like that in nested dictionaries. To bypass that the schemas that work with annotations had to be customized and some of the default marshmallow schema class methods had to be overridden. This overriding was not done properly and the overridden method was not taking into account missing/default keys and erroring out.
This fixes this problem.
I spun up a session in my deployment to test this. Having a pod with the annotations that are not marked as `required` in the marshmallow schema (such as `git-host`) does not cause the bug now. Also tested …
> fix: missing annotations handling in marshmallow

- .github/workflows/acceptance-tests.yml
- .github/workflows/ci.yml
- CHANGELOG.md
This should be merged before the 0.8.12 release of notebooks is finalized.
> chore: update changelog for 0.8.12 release

- helm-chart/renku-notebooks/values.yaml
- renku_notebooks/api/classes/server.py
This removes the disk request values from showing up by default.
Also it addresses the separate issue of the notebook sessions not launching when the PVCs for user sessions are enabled but the disk request values are not shown in the UI.
#649 will properly address the multiple edge cases of what server options are used by default in which cases. This is just a quick fix to make sure the disk requests do not show up always and that if someone is using PVCs they will still be able to do things.
> fix: remove disk request values

- .github/workflows/ci.yml
It seems that the notebook images are not tagged with latest at all. This should correct that. Now whenever images are tagged with a release tag the same images will also be published with the `latest` tag as well.
Here is the passing workflow for testing this: https://github.com/SwissDataScienceCenter/renku-notebooks/actions/runs/982073584
> chore: tag notebook images with latest when tagging a release

- Pipfile
- Pipfile.lock
Updating black requires this package to be installed in python 3.7.
This will allow the tests for #682 to pass and the update to be applied.
I tried to change the dependabot PR itself but could not get past the conflicts in the Pipfile.lock. And dependabot says that if commits are added to the PR by someone else then the conflict resolution in the Pipfile.lock is turned off.
/deploy
> chore: install typed-ast so that black can work

- helm-chart/renku-notebooks/values.yaml
- renku_notebooks/api/classes/storage.py
- renku_notebooks/api/schemas.py
- renku_notebooks/util/kubernetes_.py
- run-telepresence.sh
- tests/conftest.py
- tests/test_autosaves.py
This addresses a few bugs:
- Do not show ephemeral storage in the response that lists servers. The ephemeral storage is usually not related to what the user requested and can be set to a fixed value in the jupyterhub helm chart causing discrepancies between what the user asked when launching the session and what the api returns for the list of active servers.
- Use the username in the pvc. This was not the case before which would cause collisions between the pvcs for the same proejct/commit but for different users.
- Properly handle the data about disk size in the response when the api endpoint that list servers is called. This makes it so that things work with existing sessions from an old renku release where no disk size request has been set.
/deploy
> fix: properly display storage

- renku_notebooks/util/kubernetes_.py
I should have carefully checked what k8s requirements for PVC names are before rolling this out.
But in my tests it never occurred to me to try uppercase letters or underscores unfortunately.
Here is the regex that k8s uses to test PVC names:
```
[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
```
I.e. the only characters allowed are lowercase letters, numbers and dashes and periods.
/deploy
> fix: upper case letters in pvc name

- renku_notebooks/api/schemas.py
With the bugfix from [renku 0.8.5](https://github.com/SwissDataScienceCenter/renku/releases/tag/0.8.5) I changed the way the PVCs for user sessions are named. However I did not fully account for "grandfathering" the PVCs that were created after the initial functionality in renku 0.8.4 was rolled out.
This caused a bug in the following scenario:
1. a user launched a session with renku 0.8.4 with a PVC
2. the 0.8.5 release was applied which changed how renku names PVCs
3. after the 0.8.5 release listing the servers from the notebooks api fails if there are any active sessions with PVCs created in 0.8.4
This failed only when trying to list the servers - specifically where the storage amount is added to the server response data here (see comments starting with `####`:
```
if …
```
> fix: do not fail on pvcs created with old insecure pvc naming

- CHANGELOG.md
- helm-chart/renku-notebooks/Chart.yaml
This addresses a bug in renku notebooks where no user sessions can be properly listed when the naming convention for user session PVC changes.
With this fix if the convention changes the user sessions can still be listed - only the disk usage for the sessions that use the old naming convention will not be shown.
> chore: prep 0.8.17 release

- helm-chart/renku-notebooks/requirements.lock
- renku_notebooks/api/classes/storage.py
- renku_notebooks/api/classes/user.py
This addresses a bug where the noteboook service is unable to generate the list of active user sessions when a session exists whose project has been deleted or changed in some ways.
The bug occurs when:
- a user creates a session then deletes the project but leaves the session
- a user creates a session then deletes the branch tied to the session but leaves the session
- a user creates a session then transfers the project to a different group/namespace but leaves the session
The bug is caused by the code in the Autosave class validating the existence of several gitlab resources (i.e. branch, commit, project, etc) even if this is not always required. And in addition to doing this validation the code would raise exceptions when these validation failed. So when a user gets into one of the …
> fix: listing sessions when a project has been deleted

- renku_notebooks/api/classes/storage.py
This addresses recent bugs that have come to light.
It should address these errors:
- https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/6611/?project=4&query=is%3Aunresolved
- https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/6082/?project=4&query=is%3Aunresolved
/deploy
> fix: bugs with mistyped variable and missing branches in autosaves

- git-https-proxy/mitmproxy.js
So after testing using git LFS on https://ci-renku-2142.dev.renku.ch/ I realized that things dont work.
And the reason is that the git proxy will block requests if the user is logged in and there are requests that are not directed to the git repo (i.e the git repos url). 
This essentially blocks some requests that git/git-lfs sends directly to the object storage that backs git LFS:
```
Prevented access to: https://os.zhdk.cloud.switch.ch/dev-lfs-objects/17/49/2d449dadb0d5cb10399b25c04fae8d44f62e1c511b90106689c4207e14ad?AWSAccessKeyId=XXXXXXXX&Signature=XXXXXXXXExpires=1630928506
```
This change should let through requests (without adding the auth headers for git) if the request is not for the git repository but the user is still logged in.
> fix: git proxy should let through unrecognized requests

- renku_notebooks/api/classes/server.py
Reopened #750 to avoid the large number of commits in the PRs.
> fix: assignment of culling idle threshold for anonymous sessions

- Dockerfile.tests
- renku_notebooks/api/classes/server.py
When the `jupyter lab` command is used to start a session then the default URL for it cannot be changed and it is always `/lab` this is a problem for images that user rstudio.
/deploy renku=notebooks-operator-poc
> fix: user jupyter notebook as arg for launching a server

- .github/workflows/integration-tests.yml
- Pipfile
- Pipfile.lock
- chartpress.yaml
I think there were some issues with the kind action or I was not aware you could use chartpress to list all images and load them into kind and that is why I made the integration tests publish images. This should allow the integration tests to work without publishing images.
> chore(tests): do not publish images for integration tests

- renku_notebooks/api/classes/user.py
There can be many occasions when a gitlab project is found to not exist when the code expects it to exist.
In all such cases flasks logger is used to post an error. However this is then also picked up by sentry and it causes unnecessary notifications.
I was able to reproduce this error by:
- creating a project
- launching a sessions
- deleting the project in gitlab while remaining on the sessions page in the ui
- any request to list the sessions after this causes the error to show up in the logs and in sentry
I can confirm that even though the gitlab project is deleted but the session still exists the notebooks service properly lists the session and does not crash or return code 500. But there is an error message in the logs every time a request to the API is sent.
> fix(app): when a gitlab project does not exist log a warning not error

- helm-chart/renku-notebooks/templates/deployment.yaml
- helm-chart/renku-notebooks/values.yaml
- jupyterhub/spawners.py
- renku_notebooks/api/classes/server.py
- renku_notebooks/config.py
By using the following field in the values.yaml file
```
userSessionPersistentVolumes:
useEmptyDirSizeLimit: true
```
One can enable or disable imposing a limit on the empty dir (if empty dirs are used for user sessions).
> fix(app): make size limit optional for empty dir user session storage

- helm-chart/renku-notebooks/requirements.lock
- helm-chart/renku-notebooks/requirements.yaml
- tests/integration/test_server_options.py
Use the latest version of Amalthea. Prior to this `0.1.0-rc11`. This is almost identical to `0.1.0` without any major functionality missing. However it is better to switch to a proper release and not a release candidate.
> feat(app): use Amalthea version 0.1.0

- renku_notebooks/api/classes/server.py
This slipped through the cracks and caused the issue reported in #801.
Closes #801 
/deploy
> fix(app): master is always checked out

- helm-chart/renku-notebooks/values.yaml
So yeah this slipped through the cracks a bit. I would have preferred to use a `latest` tab, but renkulab-py does not have `latest` tags.
> fix(chart): use current fallback renku image

- .github/workflows/integration-tests.yml
- CHANGELOG.md
- helm-chart/renku-notebooks/Chart.yaml
- helm-chart/renku-notebooks/requirements.lock
- helm-chart/renku-notebooks/requirements.yaml
- helm-chart/renku-notebooks/values.yaml
New release with bugfixes and new Amalthea version.
> chore: prep 1.2.0 release

- renku_notebooks/api/classes/user.py
The gateway defaults to anonymous user id set to `""` when one is not found in the cookie for a users session. But having a token set to `""` results in improper k8s resource names. I.e. the sessions are named like `f"{user-id}-some-other-snippet"`. And when the anonymous user id is blank the resources in k8s are named starting with `-` and k8s does not allow this.
Also because of k8s naming restrictions and how the id is used in naming resources the anonymous id must start with an alphanumeric character. I added a check for this too.
/deploy (just to be sure)
> fix(app): do not accept an empty anonymous user id

- helm-chart/renku-notebooks/templates/statefulset.yaml
According to the docs here: https://docs.sentry.io/platforms/python/configuration/releases/
Setting an environment variable like `SENTRY_RELEASE` will be picked up automatically by sentry and used to distinguish and track different release versions.
> chore: track release version in sentry

- helm-chart/renku-notebooks/values.yaml
Generated automatically on a new release in renkulab-docker to update the default image used when launching a user session.
> chore(app): Update default session image to renku/renkulab-py:3.9-0.11.0

- renku_notebooks/api/notebooks.py
- renku_notebooks/api/schemas.py
- tests/integration/test_session_creation.py
Turns out this breaks the ui - specifically the session settings page. We only expected the page that lets you start a session to be affected and that was fine. But the session settings page broke and we did not notice.
> fix(app): remove S3 flag from server options

- CHANGELOG.md
- helm-chart/renku-notebooks/Chart.yaml
A new release. Needs to be rolled out at the same time as the new release on the ui.
> chore: prep 1.5.0 release

- renku_notebooks/api/notebooks.py
- renku_notebooks/api/schemas.py
- tests/integration/test_session_creation.py
So this was breaking the ui and it was commented out when merged.
Now that the ui fully supports s3 buckets it should be enabled fully. I forgot to do this earlier when I did the 1.5.0 release of notebooks. It would have been ideal to do it then.
> fix(app): enable s3 flag in server options

- CHANGELOG.md
- helm-chart/renku-notebooks/Chart.yaml
Just a new release that can fully enable/support s3 buckets mounting.
> chore: prep 1.5.1 release

- git_services/git_services/init/cloner.py
Fixes a problem with names with a middle name during the setup of the repo when launching a session.
This was introduced by the conversion of the "git clone" code from bash to python.
> fix(app): handle user names in git clone

- helm-chart/renku-notebooks/templates/configmap.yaml
In [this PR](https://github.com/SwissDataScienceCenter/renku-notebooks/pull/956/files#diff-0511dfda400363ade263615b5f47306c36858ceff72528e67296e5b1d741168f) I replaced the autosave script with python and removed the section of the configmap that contains the old bash autosave script.
However this means that sessions launched before the new renku version was released cannot create autosave branches.
I will open an issue to retire this bash script in a later release.
> fix(chart): revert the removal of autosave bash script

- CHANGELOG.md
- helm-chart/renku-notebooks/Chart.yaml
We recently replaced the autosave creation scripts with python (from bash).
But what I should have done is leave the configmap that contains the old bash script in the helm chart so that existing sessions (launched before the update to python) can still create autosaves.
This will put back the configmap to make sure all sessions can create autosaves.
> chore: prep 1.6.2 release

- .github/workflows/ci.yml
In a previous PR I cleaned up the action that lints the helm chart. 
But there is still a few things that I forgot and left over. Also the chart linting was set to happen only on merge to master or release.
Now the chart will be linted on every push. In addition since all unit tests run on every commit there is no need to build the images (and not publish them) at the last step of the job that lints the helm chart.
The images are still built on every commit when their respective unit tests run. And the images are also built when the chart or images are published.
> chore(ci): fix action that lints helm chart

- renku_notebooks/api/classes/server.py
- tests/integration/test_session_creation.py
There are unnecessary calls to the gitlab api when servers are instantiated.
In addition some properties can be cached so that they are quicker when they are called more than once.
/deploy
> fix(app): eliminate unnecessary gitlab calls

- git_services/git_services/init/cloner.py
- git_services/git_services/init/errors.py
@Panaetius as mentioned in #1055 this will make the error codes properly surface all the way to the user.
Before in all cases the error code was the generic one that had no details.
Note that the target of this PR is your feature branch.
> squashme: make error messages properly surface

- CHANGELOG.md
- helm-chart/renku-notebooks/Chart.yaml
- helm-chart/renku-notebooks/requirements.yaml
New notebooks release. Only changes to helm chart version and changelog.
/deploy renku-ui=1791-servers-resources #persist
> chore: prep release 1.8.0

- renku_notebooks/api/classes/server.py
This fixes an unhandled error that shows up in sentry:
https://sentry.dev.renku.ch/organizations/sentry/issues/339/?environment=renkulab&project=5
The error occurs in `renku_notebooks/api/classes/server.py` in get_logs at line 486. And it is a `KeyError` for `mainPod`.
With the `.get()` statements I added this should not happen again.
> fix(app): no main pod in status when getting logs

- renku_notebooks/api/classes/storage.py
Autosave branches were listed incorrectly. This was occurring because there was no check if the autosave branch belonged to the user requesting to list all autosave branches or not.
The problem was further worsened because the UI could not even determine the validity of the autosave branches it was receiving. Which blocked the launching of new sessions
> fix(app): list autosaves only for the current user

- renku_notebooks/api/classes/s3mount.py
- renku_notebooks/api/schemas/cloud_storage.py
This logic was changed recently to recognize the amazon aws s3 region. It was done under the assumption that this `x-amz-bucket-region` would only show up for AWS s3 endpoints and not in other cases. But this is not true. This field can be present even if the bucket is not hosted on AWS. Because of this some buckets that truly exist and could be reached were deemed to not exist by the notebook service.
This corrects those problems.
> fix(app): handle endpoints for s3 not on AWS

- helm-chart/renku-notebooks/requirements.yaml
- helm-chart/renku-notebooks/values.yaml
Update the helm chart used to insert self-signed CA certificates to the latest version. This latest version can run as non-root.
> chore: use CA certificates chart 0.0.3

- renku_notebooks/api/auth.py
- renku_notebooks/api/classes/user.py
- tests/integration/conftest.py
Fixes minor issues with debug statements (some of which are useless but occur way to frequently).
And also with gitlab pagination when there are a lot of items to be listed. If the `iterator` option is used when listing things then the api handles the pagination seamlessly in the generator.
Depends on #1146
> fix(app): listing autosaves and debug statements

- renku_notebooks/api/classes/server.py
- renku_notebooks/api/classes/user.py
This adds an `id` field to the user class.
The field is the keycloak user ID for registered user and for anonymous users it is the unique id that the gateway generates.
These are added in the annotations so that they can be used in publishing metrics. Currently the only user-identifying property we have is the email. But the id is better to use in logging or metrics because it better protects the user's privacy.
Also the `keycloak_user_id` field is removed because it is not used anywhere and anonymous users are not in keycloak.
> chore: use 'sub' JWT field for user id

- helm-chart/renku-notebooks/values.yaml
Generated automatically on a new release in renkulab-docker to update the default image used when launching a user session.
> chore(app): Update default session image to renku/renkulab-py:3.9-0.12.0

- renku_notebooks/api/amalthea_patches/jupyter_server.py
- renku_notebooks/api/classes/server.py
- renku_notebooks/config/__init__.py
- renku_notebooks/util/kubernetes_.py
Adds a `SESSION_URL` env var that shows full session's url.
Fixes: #1152 
> feat(app): add session url env var

- Dockerfile.tests
- git_services/git_services/sidecar/commands/base.py
We should fetch before we run `git status` in the json rpc sidecar.
> fix(sidecar): use fetch before running git status

- .github/dependabot.yaml
According to the docs here: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions
Dependabot can now keep actions up to date.
> chore: track gh actions with dependabot

- poetry.lock
- pyproject.toml
We do not publish a python package for renku-notebooks and therefore we do not need this package.
> chore: remove unused poetry-dynamic-versioning

- Dockerfile
- git_services/Dockerfile.init
- git_services/Dockerfile.sidecar
Poetry 1.2.0 seems to have a bug where the settings set in environment variables are not parsed correctly and not really respected.
For example none of the images built are supposed to come with pip and setuptools. But both can be found in them.
If the settings are applied through `poetry config <config name> <value>` then pip and setuptools are truly excluded as originally intended. 
This has no real consequences other than keeping docker image size small.
> fix: poetry flags not parsed properly

- git_services/Dockerfile.sidecar
- git_services/git_services/sidecar/errors.py
There were some issues running renku cli commands from within the git rpc sidecar.
These were the result of:
- the python git library used by renku trying to use `bash` and the alpine images not having `bash` by default, after installing bash in the image (which added only 1MB to the size) I did not see this again
- the renku cli not being on the path - after I adjusted the path for the image everything works
cc @ciyer
> fix(sidecar): renku needs to be on path

- helm-chart/renku-notebooks/values.yaml
Generated automatically on a new release in renkulab-docker to update the default image used when launching a user session.
> chore(app): Update default session image to renku/renkulab-py:3.9-0.13.0

- helm-chart/renku-notebooks/requirements.yaml
- renku_notebooks/api/amalthea_patches/general.py
- renku_notebooks/api/amalthea_patches/init_containers.py
- renku_notebooks/api/classes/server.py
- renku_notebooks/api/schemas/servers_get.py
- renku_notebooks/config/__init__.py
- renku_notebooks/config/dynamic.py
closes #1135 
Provides more detailed information about server status.
Example status section of server response:
```json
"status": {
"details": [{  # NEW
"status": "ready",
"step": "Initialization"
}, {
"status": "ready",
"step": "Downloading session image"
}, {
"status": "executing",
"step": "Cloning and configuring the repository"
}, {
"status": "waiting",
"step": "Git credentials services"
}, {
"status": "waiting",
"step": "Authentication and proxying services"
}, {
"status": "waiting",
"step": "Auxiliary session services"
}, {
"status": "waiting",
"step": "Starting session"
}],
"message": "Containers with non-ready statuses: git-proxy, git-sidecar, jupyter-server, oauth2-proxy.",
"readyNumContainers": 2,  # NEW
"state": "starting",
"totalNumContainers": 7  # NEW
},
```
Possible step …
> feat(app): detailed status messages

- .github/workflows/integration-tests.yml
The integration tests for the notebooks use their own values, since they only deploy the notebook service helm chart and test against it.
I forgot to modify the values after the upgrade of our gitlab.
This should fix the integration tests.
> chore(ci): fix integration tests

- .gitignore
- renku_notebooks/api/notebooks.py
Clears cross site scripting vulnerabilities reported by snyk.
These were impossible to occur because they are related to the `server_name` parameter being used to query k8s for the specific server name and then return the server.
So if a malformed or malicious string was passed then the server would simply not be found in k8s.
Either way by using `jsonify` from `flask` if there are any malicious content in the parameter and if that somehow finds its way back into the the response then the content would be properly escaped.
I ran `SNYK_CFG_ORG=renku snyk code test` locally after making these changes to make sure they are properly addressed and they are.
/deploy #persist renku-gateway=master renku=master
> fix(app): snyk vulnerabilities

- git_services/git_services/init/cloner.py
I recently merged an old PR about checking the LFS size and disk size available before we pull the LFS data (#1226). 
#1226 added runs `git lfs` commands through the thin git wrapper we have. But after #1226 was opened but before it was merged we made the git wrapper accept only a list of arguments as parameters rather than all parameters as one string. When I merged #1226 there were 2-3 `git lfs commands` that were passing a single string with space separated parameters rather than a list.
This corrects that problem so that the git wrapper is used properly.
> fix(sidecar): use list of args in git LFS commands

- renku_notebooks/api/amalthea_patches/jupyter_server.py
- renku_notebooks/api/classes/server.py
- renku_notebooks/api/notebooks.py
- renku_notebooks/errors/programming.py
- renku_notebooks/errors/user.py
- tests/unit/test_server_class/test_manifest.py
Checks that user doesn't override env vars sets by Amalthea patches and that Amalthea patches don't override the same env var with different values (in the same container).
Fixes: #1311
> feat(session): fail when injecting env vars that exist in session

- git_services/git_services/init/cloner.py
If an anonymous user requests a session at a commit sha other than head then they would always get head.
This happened only for anonymous sessions. This fixes the problem.
> fix(sidecar): anon users clone repo at correct SHA

- helm-chart/renku-notebooks/values.yaml
Generated automatically on a new release in renkulab-docker to update the default image used when launching a user session.
> chore(app): Update default session image to renku/renkulab-py:3.9-0.14.0

- git_services/git_services/cli/__init__.py
- git_services/git_services/init/cloner.py
This is an issue that Till discovered that if there are LFS files in the autosave branch they do not get recovered. The reason for this is that by default we do not pull LFS files (even when recovering an autosave). So any files that were checked in LFS and created with the autosave are lost and only the LFS pointers (which are not valid anymore) are left. And the pointers point to the non-existent branch and LFS data.
This corrects the problem.
> fix(app): properly recover LFS from autosave

- renku_notebooks/api/classes/server.py
Adds the quota and user ids to the pod labels. These can then be used to more easily filter workloads for specific users or resource pools. 
closes #1600
> chore: add resource quota label

- helm-chart/renku-notebooks/values.yaml
This really has no effect on things because chartpress builds and publishes the right things in the CI pipeline.
But it is nicer to not have a weird repo for the images.
> chore: use renku dockerhub images

- .github/workflows/acceptance-tests.yml
- renku_notebooks/api/amalthea_patches/cloudstorage.py
- renku_notebooks/api/classes/cloud_storage/__init__.py
- renku_notebooks/api/classes/cloud_storage/azure_blob.py
- renku_notebooks/api/classes/cloud_storage/s3mount.py
- renku_notebooks/api/notebooks.py
- renku_notebooks/api/schemas/cloud_storage.py
- reorders patches to create secrets before creating dataset CRD
- fixes `target_path` to instead ufse `mount_folder` property (the formet didn't exist)
- Wraps marshmallow ValidationErrors in UserInputError
/deploy renku=data-service-chart renku-gateway=master renku-notebooks=master renku-data-services=main renku-ui=master extra-values=dataService.image.pullPolicy=Always,global.gitlab.url=gitlab.dev.renku.ch,notebooks.cloudstorage.s3.enabled=true,amalthea.extraChildResources[0].group=com.ie.ibm.hpsys,amalthea.extraChildResources[0].name=datasets,notebooks.cloudstorage.s3.installDatashim=false
> fix secret order and mount path check

- git_services/git_services/sidecar/config.py
- renku_notebooks/config/dynamic.py
Helm will convert a large integer (specified normally in the values file) like `3000000` to scientific notation like `3e6` in the templates.
And python `int()` crashes when it sees `3e6` and you have to use `float()` to parse it.
Also I have the same function repeated because it is in two separate modules that are at the same level and they share no code. So to not repeat that one simple function I would have to do a lot unnecessary gymnastics just for one small really simple function.
> fix: scientific notation integer parsing in config

- CHANGELOG.md
- helm-chart/renku-notebooks/Chart.yaml
- helm-chart/renku-notebooks/values.yaml
A new bugfix release to allow proper templating of tolerations and affinities that are stored in the CRC.
> chore: prep 1.20.1 release

- renku_notebooks/api/amalthea_patches/general.py
- renku_notebooks/api/classes/server.py
This adds a larger value for shared memory in the jupyter session.
This is needed when multiple gpus are used for training or simply when a lot of data is being loaded into the gpus for large models.
We have had complaints that training jobs and models are failing because this value is too low.
We have semi-arbitrarily decided to set a limit of half the memory requested for this.
/deploy
> fix: patch in a larger value for /dev/shm

- renku_notebooks/api/classes/server.py
> fix: project path case sensitivity

- renku_notebooks/config/__init__.py
/deploy renku=add-missing-default-value renku-data-services=v0.9.0
> fix: make dataconf ignore unexpected env vars

- renku_notebooks/api/amalthea_patches/cloudstorage.py
- renku_notebooks/api/amalthea_patches/git_proxy.py
- renku_notebooks/api/amalthea_patches/git_sidecar.py
- renku_notebooks/api/amalthea_patches/init_containers.py
- renku_notebooks/api/classes/server.py
Fixes #1891.
Also moves conditions for empty patches inside their respective functions.
/deploy renku=master
> fix: do not add storage mounts patches when a session has no repository

- .github/workflows/ci.yml
- liveness-detector/Dockerfile
- liveness-detector/LICENSES/Apache-2.0.txt
- liveness-detector/README.md
- liveness-detector/liveness_detector/__init__.py
- liveness-detector/liveness_detector/activity_watcher.py
- liveness-detector/pixi.lock
- liveness-detector/pyproject.toml
- liveness-detector/scripts/entrypoint-hook.sh
- liveness-detector/scripts/entrypoint-init-container.sh
- liveness-detector/test/test_server.py
- liveness-detector/test/test_watcher.py
Adds a component that can be used either as a sidecar for liveness detection by watching workdir files for modifications or as an init container to watch for load average + activity on pty on top of that.
> feat: add liveness-detector

- git_services/git_services/init/cloner.py
https://github.com/SwissDataScienceCenter/renku-notebooks/pull/1971/files#diff-4040874efe86d379ae1fae844f06544085c1d5e43db0c002894c6be44c28e507R140-R141 this is the only change, everything else is automated formatting.
fixes #1955
> fix: don't fail clone process if access token doesn't exist

- .github/workflows/acceptance-tests.yml
- renku_notebooks/api/amalthea_patches/general.py
Currently container #1 is `oauth-proxy` while JupyterServer, is #0.
Additionally use half of the memory requested by the pod instead of half of the storage.
Since we rely on memory there is no need to tie the increased /dev/shm to requesting storage in the session.
NOTE: This system of patching the manifest is very brittle and the bug being fixed by this commit might appear again as soon as the containers sorting changes. We should think about a different way of interacting with the manifests of the user-sessions.
/deploy renku=leafty/fix-renku-jupyterserver
> fix: Mount /dev/shm to the correct container.

- renku_notebooks/api/classes/image.py
- tests/unit/test_public_image_checks.py
This occurs because some images (most likely when they support multiple architectures) have an index instead of just a manifest. An OCI index refers to a set of images. But when we were checking for images we were only checking for the manifest and did not have the option to support an index content type.
/deploy
> fix: image checks for some oci images failed

- renku_notebooks/api/classes/data_service.py
- renku_notebooks/api/notebooks.py
Add support for mounting data connectors (instead of `storages_v2`) with Renku 2.0 sessions.
/deploy renku-data-services=leafty/feat-namespaced-data-connectors-5 renku-ui=ciyer/data-connector-secrets
> feat!: support data connectors

- pyproject.toml
- renku_notebooks/__init__.py
- renku_notebooks/api/classes/k8s_client.py
- renku_notebooks/config/__init__.py
- renku_notebooks/config/dynamic.py
> fix: properly use gevent and allow configuring k8s cache bypass

- git_services/git_services/init/cloner.py
- git_services/git_services/sidecar/errors.py
- git_services/tests/test_init_clone.py
- git_services/tests/test_rpc_server.py
Closes #2006, closes #2011.
Allows the `git-clone` step to proceed when a git repository is empty and fix guessing the folder name.
/deploy #notest renku=release-0.65.0 renku-data-services=leafty/fix-cloudstorage-in-workdir
> fix: handle empty git repository and handle ending slash

- renku_notebooks/api/amalthea_patches/init_containers.py
backport https://github.com/SwissDataScienceCenter/renku-data-services/pull/701
Tested here: https://renku-ci-nb-2013.dev.renku.ch/projects/flora.thiebaut/a-new-playground-project/sessions/new
Also tested in the `renku` repository: https://github.com/SwissDataScienceCenter/renku/actions/runs/13702131618/job/38320139809
/deploy renku=build/session-env-builders
> fix: backport SwissDataScienceCenter/renku-data-services#701

- k8s-watcher/cache.go
- k8s-watcher/config.go
This is necessary because the new and old servers have different labels that indicate the user ID that the session belongs to. So to stay compatible with older sessions and to enable the switch to the data service for v1 sessions this change is required.
> feat: use different user labels in k8s watcher

- k8s-watcher/config.go
- k8s-watcher/server.go
- k8s-watcher/server_routes.go
Fixes an issue from #2007.
When image building is not enabled in the RenkuLab instance, do not cache Shipwright BuildRuns and Tekton TaskRuns and do not provide the corresponding API endpoints.
This was already done in a release branch. But it was never merged into master.
> fix: toggle on/off watching resources for image builds (#2014)
